site_name: polars-api
repo_url: https://github.com/diegoglozano/polars-api
site_url: https://diegoglozano.github.io/polars-api
site_description: Polars extension for dealing with REST APIs
site_author: Diego Garcia Lozano
edit_uri: edit/main/docs/
repo_name: diegoglozano/polars-api
copyright: Maintained by <a href="https://diegoglozano.com">diegoglozano</a>.

nav:
  - Home: index.md
  - Documentation: documentation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [polars_api]
          options:
            docstring_style: numpy
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/diegoglozano/polars-api
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/polars-api

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
